message: null
---
spring:
  config:
    activate:
      on-profile: default
message: default profile message
---
spring:
  config:
    activate:
      on-profile: local
message: local profile message
---
spring:
  config:
    activate:
      on-profile: test
message: test profile message
---
spring:
  config:
    activate:
      on-profile: local & testx
message: local, test profile message
