
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
message: null
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    # show-sql: true
---
spring:
  config:
    activate:
      on-profile: default
message: default profile message
---
spring:
  config:
    activate:
      on-profile: local
message: local profile message
---
spring:
  config:
    activate:
      on-profile: test
message: test profile message
---
spring:
  config:
    activate:
      on-profile: local & testx
message: local, test profile message
